### ISSUE TITLE
Unhandled Connection Refused Errors

### ISSUE THREAD

**Issue by NeonDaniel** [OpenVoiceOS/ovos-PHAL-plugin-ipgeo#12]
Observed the following exception trace today. Need to determine if this is temporary or if the upstream API has changed. Consider also making the endpoint configurable and looking for other options to fall back to.
```
2024-05-10 09:27:20.218 - enclosure - ovos_phal_plugin_ipgeo:on_reset:52 - ERROR - HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7243bb80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Traceback (most recent call last):
  File "/home/neon/venv/lib/python3.10/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "/home/neon/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/home/neon/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/neon/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/home/neon/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/home/neon/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/home/neon/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "/home/neon/venv/lib/python3.10/site-packages/urllib3/connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
  File "/home/neon/venv/lib/python3.10/site-packages/urllib3/connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f7243bb80>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/neon/venv/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/neon/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/home/neon/venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7243bb80>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neon/venv/lib/python3.10/site-packages/ovos_phal_plugin_ipgeo/__init__.py", line 39, in on_reset
    location = self.ip_geolocate()
  File "/home/neon/venv/lib/python3.10/site-packages/ovos_phal_plugin_ipgeo/__init__.py", line 61, in ip_geolocate
    ip = requests.get('https://api.ipify.org').text
  File "/home/neon/venv/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/neon/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/neon/venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/neon/venv/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/neon/venv/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7243bb80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-05-10 09:27:20.278 - enclosure - ovos_phal_plugin_ipgeo:on_reset:54 - DEBUG - Emitting error response

```

**Comment by JarbasAl** [comment]
it is configurable https://github.com/OpenVoiceOS/ovos-utils/blob/dev/ovos_utils/network_utils.py#L9

**Comment by NeonDaniel** [comment]
Wrapping up some changes, but have this working currently at: https://hana.neonaialpha.com/util/client_ip

api.ipify.org appears to be down; I get cert errors and then a default nginx page

**Comment by NeonDaniel** [comment]
After resolving the IP lookup issue, a different exception is thrown:
```
2024-05-14 18:03:51.947 - enclosure - ovos_phal_plugin_ipgeo:ip_geolocate:67 - ERROR - Backend Geolocation API error!
Traceback (most recent call last):
  File "/home/neon/venv/lib/python3.10/site-packages/ovos_phal_plugin_ipgeo/__init__.py", line 65, in ip_geolocate
    return api.get_ip_geolocation(ip)
  File "/home/neon/venv/lib/python3.10/site-packages/ovos_backend_client/api.py", line 392, in get_ip_geolocation
    return self.backend.ip_geolocation_get(ip)
  File "/home/neon/venv/lib/python3.10/site-packages/ovos_utils/__init__.py", line 130, in wrapped_f
    return f(*args, **kwargs)
  File "/home/neon/venv/lib/python3.10/site-packages/ovos_backend_client/backends/offline.py", line 308, in ip_geolocation_get
    region_data = {"code": data["region"],
KeyError: 'region'
2024-05-14 18:03:52.465 - enclosure - ovos_phal_plugin_ipgeo:on_reset:54 - ERROR - 'region'
Traceback (most recent call last):
  File "/home/neon/venv/lib/python3.10/site-packages/ovos_phal_plugin_ipgeo/__init__.py", line 65, in ip_geolocate
    return api.get_ip_geolocation(ip)
  File "/home/neon/venv/lib/python3.10/site-packages/ovos_backend_client/api.py", line 392, in get_ip_geolocation
    return self.backend.ip_geolocation_get(ip)
  File "/home/neon/venv/lib/python3.10/site-packages/ovos_utils/__init__.py", line 130, in wrapped_f
    return f(*args, **kwargs)
  File "/home/neon/venv/lib/python3.10/site-packages/ovos_backend_client/backends/offline.py", line 308, in ip_geolocation_get
    region_data = {"code": data["region"],
KeyError: 'region'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neon/venv/lib/python3.10/site-packages/ovos_phal_plugin_ipgeo/__init__.py", line 41, in on_reset
    location = self.ip_geolocate()
  File "/home/neon/venv/lib/python3.10/site-packages/ovos_phal_plugin_ipgeo/__init__.py", line 70, in ip_geolocate
    return api.get_ip_geolocation(ip)
  File "/home/neon/venv/lib/python3.10/site-packages/ovos_backend_client/api.py", line 392, in get_ip_geolocation
    return self.backend.ip_geolocation_get(ip)
  File "/home/neon/venv/lib/python3.10/site-packages/ovos_utils/__init__.py", line 130, in wrapped_f
    return f(*args, **kwargs)
  File "/home/neon/venv/lib/python3.10/site-packages/ovos_backend_client/backends/offline.py", line 308, in ip_geolocation_get
    region_data = {"code": data["region"],
KeyError: 'region'
```

This originates in ovos-backend-client but should probably be handled better here
